In [1]:
import pandas as pd

#function(file,year)
#run the fucntion 10 times to get 10 df
#change column name,remove 1st row,add date cloumn, add year column
#combine 10 dataframes

In [27]:
#Declar the file path of each year
file_path_2019='raw_data/USHousing-2019.csv'
file_path_2018='raw_data/USHousing-2018.csv'
file_path_2017='raw_data/USHousing-2017.csv'
file_path_2016='raw_data/USHousing-2016.csv'
file_path_2015='raw_data/USHousing-2015.csv'
file_path_2014='raw_data/USHousing-2014.csv'
file_path_2013='raw_data/USHousing-2013.csv'
file_path_2012='raw_data/USHousing-2012.csv'
file_path_2011='raw_data/USHousing-2011.csv'
file_path_2010='raw_data/USHousing-2010.csv'

In [28]:
def data_transf(file_path,year):
    origin_df=pd.read_csv(file_path)
    
    extract_df=origin_df[['NAME','DP04_0001E','DP04_0002E','DP04_0002PE','DP04_0007E','DP04_0008E','DP04_0009E',
                       'DP04_0010E','DP04_0011E','DP04_0012E','DP04_0013E','DP04_0014E','DP04_0015E',
                       'DP04_0039E','DP04_0040E','DP04_0041E','DP04_0042E','DP04_0043E','DP04_0044E',
                       'DP04_0080E','DP04_0081E','DP04_0082E','DP04_0083E','DP04_0084E','DP04_0085E','DP04_0086E',
                       'DP04_0087E','DP04_0088E','DP04_0089E','DP04_0110E','DP04_0111E','DP04_0112E',
                       'DP04_0113E','DP04_0114E','DP04_0115E','DP04_0116E','DP04_0117E','DP04_0118E','DP04_0119E',
                       'DP04_0120E','DP04_0121E','DP04_0122E','DP04_0123E','DP04_0124E','DP04_0125E']]
    
    renamed_df=extract_df.rename(columns={'DP04_0001E':'Total Housing Units','DP04_0002E':'Occupied Units','DP04_0002PE':'Occupied Percent','DP04_0007E':'1-unit det',
                                'DP04_0008E':'1-unit att','DP04_0009E':'2 units','DP04_0010E':'3 or 4 units','DP04_0011E':'5 to 9 units','DP04_0012E':'10 to 19 units',
                                'DP04_0013E':'20 or more units','DP04_0014E':'Mobile home','DP04_0015E':'boat,RV,van,etc.','DP04_0039E':'No bedroom','DP04_0040E':'1 bedroom',
                                'DP04_0041E':'2 bedrooms','DP04_0042E':'3 bedrooms','DP04_0043E':'4 bedrooms','DP04_0044E':'5 or more bedrooms','DP04_0080E':'owner-occupied units',
                                'DP04_0081E':'Less than $50k','DP04_0082E':'$50,000 to $99,999','DP04_0083E':'$100,000 to $149,999','DP04_0084E':'$150,000 to $199,999',
                                'DP04_0085E':'$200,000 to $299,999','DP04_0086E':'$300,000 to $499,999','DP04_0087E':'$500,000 to $999,999','DP04_0088E':'$1M or more',
                                'DP04_0089E':'Median (dollars)','DP04_0110E':'units with mortgage with SMOCAPI','DP04_0111E':'SMOCAPI:less than 20 perc(m)','DP04_0112E':'SMOCAPI:20 to 24.9 perc(m)',
                                'DP04_0113E':'SMOCAPI:25 to 29.9 perc(m)','DP04_0114E':'SMOCAPI:30 to 34.9 perc(m)','DP04_0115E':'SMOCAPI:35 perc(m) or more','DP04_0116E':'SMOCAPI not computed(m)',
                                'DP04_0117E':'units without mortgage with SMOCAPI','DP04_0118E':'SMOCAPI:less than 10 perc(nm)','DP04_0119E':'SMOCAPI:10 to 14.9 perc(nm)',
                                'DP04_0120E':'SMOCAPI:15 to 19.9 perc(nm)','DP04_0121E':'SMOCAPI:20 to 24.9 perc(nm)','DP04_0122E':'SMOCAPI:25 to 29.9 perc(nm)',
                                'DP04_0123E':'SMOCAPI:30 to 34.9 perc(nm)','DP04_0124E':'SMOCAPI:35 perc(nm) or more','DP04_0125E':'SMOCAPI not computed(nm)'})
    
    renamed_df['Year']=year
    renamed_df['Date']=f'{year}-01-01'
    
    row_df=renamed_df.iloc[1:53,:]
    
    
    return row_df

In [31]:
#cleanup/transform each dataset
final_2019=data_transf(file_path_2019,2019)
final_2018=data_transf(file_path_2019,2018)
final_2017=data_transf(file_path_2019,2017)
final_2016=data_transf(file_path_2019,2016)
final_2015=data_transf(file_path_2019,2015)
final_2014=data_transf(file_path_2019,2014)
final_2013=data_transf(file_path_2019,2013)
final_2012=data_transf(file_path_2019,2012)
final_2011=data_transf(file_path_2019,2011)
final_2010=data_transf(file_path_2019,2010)

In [44]:
final_df=pd.concat([final_2019,final_2018,final_2017,final_2016,final_2015,final_2014,final_2013,final_2012,final_2011,final_2010])
final_df.shape

(520, 47)

In [45]:
reindex=final_df.reset_index(drop=True)
reindex.tail()

,NAME,Total Housing Units,Occupied Units,Occupied Percent,1-unit det,1-unit att,2 units,3 or 4 units,5 to 9 units,10 to 19 units,...,SMOCAPI:less than 10 perc(nm),SMOCAPI:10 to 14.9 perc(nm),SMOCAPI:15 to 19.9 perc(nm),SMOCAPI:20 to 24.9 perc(nm),SMOCAPI:25 to 29.9 perc(nm),SMOCAPI:30 to 34.9 perc(nm),SMOCAPI:35 perc(nm) or more,SMOCAPI not computed(nm),Year,Date
515,Washington,3195098,2932477,91.8,1984984,129382,71700,112448,152584,160802,...,281949,116837,65928,37084,23310,14522,51354,5813,2010,2010-01-01
516,West Virginia,894983,728175,81.4,638080,18937,19452,28169,25424,15196,...,161240,51486,25295,13350,8179,5210,17989,4024,2010,2010-01-01
517,Wisconsin,2725153,2386623,87.6,1805692,107864,180832,98470,130731,97095,...,259857,131950,67613,38934,25867,15589,54027,4332,2010,2010-01-01
518,Wyoming,280281,233128,83.2,183348,15253,5456,11948,11271,6338,...,37771,11519,6123,2841,2792,1300,5220,823,2010,2010-01-01
519,Puerto Rico,1559505,1170982,75.1,1078971,182306,44764,40678,68388,52679,...,267830,81385,37387,26328,13275,8340,34158,26383,2010,2010-01-01

In [47]:
reindex.to_csv('final_dataset.csv',index=False)